### ISSUE TITLE
Support non-fixed schema for indexed document

### ISSUE THREAD

**Issue by augustine-tran** [LinkedInAttic/indextank-engine#22]
First step: I added a document {text: 'something', author: 'rua'}
Second ste: I added a document with new field {text: 'something', author: 'rua', type: '1'}
Now, I query http://localhost:20220/v1/indexes/candidates/search?q=author:rua&fetch=*, I got 503 Service unavaiable
I think I can update rest of document with new field, but that is not a best way.

**Comment by iladriano** [comment]
Got it, will check & fix.

**Comment by iladriano** [comment]
This happens when the engine is restarted without "cleaning" the persisted index data.

When you start the engine and there is previous index data, it could pick up the old documents and those are not in the in-memory storage, so an exception is raised when trying to fetch said documents.

Can you try the same test with a clean index (target/base should be removed before launching the engine)?

I will also update that exception's visibility.

**Comment by augustine-tran** [comment]
Dear adrani,

Thanks for quickly reply. I'm also sorry for my basic English. But in my scenario, I did not restart server, I just added documents one by one. Just the second document had new field.

**Comment by iladriano** [comment]
This is what I've tried to verify the issue doesn't reproduce (unless the server is restarted):

curl -d "{\"docid\":\"post2\", \"fields\":{\"text\":\"I love Fallout\"}}" -v -X PUT http://localhost:20220/v1/indexes/idx/docs
curl -d "{\"docid\":\"post1\", \"fields\":{\"text\":\"I love Planescape Torment\"}}" -v -X PUT http://localhost:20220/v1/indexes/idx/docs
curl -d "{\"docid\":\"post1\", \"fields\":{\"text\":\"I love Planescape Torment\", \"type\": \"1\"}}" -v -X PUT http://localhost:20220/v1/indexes/idx/docs

Then this queries:
http://localhost:20220/v1/indexes/idx/search?q=love&fetch=*
http://localhost:20220/v1/indexes/idx/search?q=I+love+Planescape+Torment&fetch=*

With a fresh index, that works. If your test is substantially different please add the full details to reproduce it.

**Comment by augustine-tran** [comment]
Dear adrani,
You're right. Many thanks. 

But if I delete target/base directory, so 
- How can I remain my index data? Are there any options when start index?
- What are difference between Standalone RestAPI and Thrift api? I mean that:  class:com.flaptor.indextank.index.IndexEngine and class: com.flaptor.indextank.api.Launcher
- How can I backup index data?

Regards,

**Comment by iladriano** [comment]
Index data can be retained by replacing the in-memory storage with a persistent implementation. I'm working on providing that option.

By design, a user access an index through the REST API. Across the platform stack we've used Thrift to integrate the engine. The standalone API option skips the Thrift layer and exposes the REST API directly.

Gracefully: index structure is persisted with a shutdown hook.
Ungracefully: a recovery could take place (ex.: fetching documents from the persistent storage mentioned before).

**Comment by augustine-tran** [comment]
Awesome! Thanks for your help.
